Use a more standardized method of determining that we're running in a docker container

diff --git a/build/cme-entrypoint b/build/cme-entrypoint
--- a/build/cme-entrypoint
+++ b/build/cme-entrypoint
@@ -1,8 +1,10 @@
 #!/bin/bash
+set -ex
 
-# Set DOCKER to let cme Python code know
-# when it's running inside of a container
-export DOCKER=1
+if ! [ -f /.dockerenv ] ; then
+  echo "ERROR: This script must run inside a docker container." >&2
+  exit 1
+fi
 
 if [ "$1" = 'cme' ]; then
 	exec "$@"
